input {
  file {
    path => "/logs/dqc/dqc_dlq.log"
    start_position => "beginning"
    sincedb_path => "/tmp/logstash-dqc-dlq.sincedb"
    codec => "json"
  }
}

filter {
  if [log_type] != "dqc_dlq" {
    drop { }
  }

  mutate {
    add_field => {
      "pipeline" => "dqc"
      "event_category" => "dead_letter_queue"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "dqc-dlq-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
