from sqlalchemy.orm import declarative_base
from sqlalchemy import (
    Column,
    Integer,
    BigInteger,
    Float,
    Boolean,
    Text,
    Date,
    DateTime,
    Time,
)

Base = declarative_base()



class Source(Base):
    __tablename__ = "source"

    id = Column(Integer, primary_key=True, autoincrement=True)
    export_date = Column(Date, nullable=False)
    workspace_id = Column(Text, nullable=False)
    node_id = Column(Text, nullable=False)
    version_id = Column(Text, nullable=False)
    name_label = Column(Text, nullable=False)
    name_tech = Column(Text, nullable=False)
    path_full = Column(Text, nullable=False)
    path_type = Column(Text, nullable=False)
    entity_type = Column(Text, nullable=False)
    data_type = Column(Text, nullable=False)
    dlk_api_path = Column(Text, nullable=False)
    dlk_url = Column(Text, nullable=False)
    children_count = Column(BigInteger, nullable=False)
    status = Column(Text, nullable=False)
    description = Column(Text, nullable=False)
    created_at = Column(Text, nullable=False)
    updated_at = Column(Text, nullable=False)
    doc_pct = Column(Float, nullable=False)
    security_comment = Column(Text, nullable=False)
    app_code = Column(Text, nullable=False)
    techno = Column(Text, nullable=True)
    validated_at = Column(Date, nullable=True)
    host_mode = Column(Text, nullable=False)
    security_level = Column(Text, nullable=False)
    tech_code = Column(Text, nullable=False)
    train_app = Column(Text, nullable=False)
    hierarchy_level = Column(Integer, nullable=False)
    hierarchy_name = Column(Text, nullable=False)


class Container(Base):
    __tablename__ = "container"

    id = Column(Integer, primary_key=True, autoincrement=True)
    export_date = Column(Date, nullable=True)
    workspace_id = Column(Text, nullable=False)
    node_id = Column(Text, nullable=False)
    version_id = Column(Text, nullable=False)
    name_label = Column(Text, nullable=False)
    name_tech = Column(Text, nullable=False)
    path_full = Column(Text, nullable=False)
    path_type = Column(Text, nullable=False)
    entity_type = Column(Text, nullable=False)
    data_type = Column(Text, nullable=False)
    dlk_api_path = Column(Text, nullable=False)
    dlk_url = Column(Text, nullable=False)
    children_count = Column(BigInteger, nullable=False)
    status = Column(Text, nullable=False)
    description = Column(Text, nullable=True)
    created_at = Column(Text, nullable=True)
    updated_at = Column(Text, nullable=True)
    doc_pct = Column(Float, nullable=False)
    app_code = Column(Text, nullable=True)
    techno = Column(Text, nullable=True)
    validated_at = Column(Date, nullable=True)
    train_app = Column(Text, nullable=True)
    parent_node_id = Column(Text, nullable=False)
    parent_type = Column(Text, nullable=False)
    parent_data_type = Column(Text, nullable=False)
    hierarchy_level = Column(Integer, nullable=False)
    hierarchy_name = Column(Text, nullable=False)


class Structure(Base):
    __tablename__ = "structure"

    id = Column(Integer, primary_key=True, autoincrement=True)
    export_date = Column(Date, nullable=False)
    workspace_id = Column(Text, nullable=False)
    node_id = Column(Text, nullable=False)
    version_id = Column(Text, nullable=False)
    name_label = Column(Text, nullable=False)
    name_tech = Column(Text, nullable=False)
    path_full = Column(Text, nullable=False)
    path_type = Column(Text, nullable=False)
    entity_type = Column(Text, nullable=False)
    data_type = Column(Text, nullable=False)
    dlk_api_path = Column(Text, nullable=False)
    dlk_url = Column(Text, nullable=False)
    children_count = Column(BigInteger, nullable=False)
    status = Column(Text, nullable=False)
    summary = Column(Text, nullable=False)
    description = Column(Text, nullable=False)
    created_at = Column(Text, nullable=False)
    updated_at = Column(Text, nullable=False)
    validated_at = Column(Date, nullable=True)
    train_app = Column(Text, nullable=False)
    doc_pct = Column(Float, nullable=True)
    primary_key_name = Column(Text, nullable=True)
    tech_comment = Column(Text, nullable=False)
    parent_node_id = Column(Text, nullable=False)
    parent_type = Column(Text, nullable=False)
    parent_data_type = Column(Text, nullable=False)
    kafka_topic_type = Column(Text, nullable=True)
    doc_pct_func = Column(Float, nullable=False)
    doc_pct_data = Column(Float, nullable=True)
    doc_pct_label_fr = Column(Float, nullable=True)
    doc_pct_glossary = Column(Float, nullable=True)
    doc_pct_source = Column(Float, nullable=True)
    kafka_conforms_to_entity = Column(Text, nullable=False)
    kafka_data_exhaustive = Column(Text, nullable=False)
    kafka_has_description = Column(Text, nullable=False)
    kafka_schema_registry_compliant = Column(Text, nullable=False)
    is_kafka_topic = Column(Boolean, nullable=False)
    hierarchy_level = Column(Integer, nullable=False)
    hierarchy_name = Column(Text, nullable=False)


class Field(Base):
    __tablename__ = "field"

    id = Column(Integer, primary_key=True, autoincrement=True)
    export_date = Column(Date, nullable=False)
    workspace_id = Column(Text, nullable=False)
    node_id = Column(Text, nullable=False)
    version_id = Column(Text, nullable=False)
    name_label = Column(Text, nullable=False)
    name_tech = Column(Text, nullable=False)
    path_full = Column(Text, nullable=False)
    path_type = Column(Text, nullable=False)
    entity_type = Column(Text, nullable=False)
    data_type = Column(Text, nullable=False)
    dlk_api_path = Column(Text, nullable=False)
    dlk_url = Column(Text, nullable=False)
    children_count = Column(Text, nullable=True)
    status = Column(Text, nullable=False)
    summary = Column(Text, nullable=False)
    description = Column(Text, nullable=False)
    created_at = Column(Text, nullable=True)
    updated_at = Column(Text, nullable=True)
    app_code = Column(Text, nullable=True)
    validated_at = Column(Date, nullable=True)
    tech_comment = Column(Text, nullable=False)
    security_level = Column(Text, nullable=False)
    security_comment = Column(Text, nullable=False)
    train_app = Column(Text, nullable=False)
    is_mandatory = Column(Boolean, nullable=True)
    is_primary_key = Column(Boolean, nullable=True)
    is_foreign_key = Column(Boolean, nullable=True)
    is_technical = Column(Boolean, nullable=True)
    is_gdpr_personal = Column(Boolean, nullable=True)
    is_gdpr_sensitive = Column(Boolean, nullable=True)
    class_propagation = Column(Text, nullable=False)
    dacp_propagation = Column(Text, nullable=False)
    col_size = Column(BigInteger, nullable=True)
    col_data_type = Column(Text, nullable=False)
    col_type_size = Column(Text, nullable=True)
    parent_node_id = Column(Text, nullable=False)
    parent_type = Column(Text, nullable=False)
    parent_data_type = Column(Text, nullable=False)
    is_local_data = Column(Boolean, nullable=True)
    is_golden_source = Column(Boolean, nullable=True)
    governance_risk_score = Column(Integer, nullable=False)
    hierarchy_level = Column(Integer, nullable=False)
    hierarchy_name = Column(Text, nullable=False)


class Link(Base):
    __tablename__ = "link"

    id = Column(Integer, primary_key=True, autoincrement=True)
    export_date = Column(Date, nullable=True)
    workspace_id = Column(Text, nullable=False)
    src_node_id = Column(Text, nullable=False)
    src_name_label = Column(Text, nullable=False)
    src_name_tech = Column(Text, nullable=False)
    src_entity_type = Column(Text, nullable=False)
    src_data_type = Column(Text, nullable=False)
    link_type = Column(Text, nullable=False)
    tgt_node_id = Column(Text, nullable=False)
    tgt_name_label = Column(Text, nullable=True)
    tgt_name_tech = Column(Text, nullable=True)
    tgt_entity_type = Column(Text, nullable=False)
    tgt_data_type = Column(Text, nullable=True)
    tgt_path_type = Column(Text, nullable=False)
    tgt_path = Column(Text, nullable=False)
    hierarchy_level = Column(Integer, nullable=False)
    hierarchy_name = Column(Text, nullable=False)


class Usage(Base):
    __tablename__ = "usage"

    id = Column(Integer, primary_key=True, autoincrement=True)
    usage_uuid = Column(Text, nullable=False)
    usage_name = Column(Text, nullable=False)
    usage_tech_name = Column(Text, nullable=False)
    usage_path = Column(Text, nullable=False)
    usage_type_path = Column(Text, nullable=False)
    usage_kind = Column(Text, nullable=False)
    status = Column(Text, nullable=False)
    classification_level = Column(Text, nullable=True)
    classification_level_dlk = Column(Text, nullable=True)
    classification_comment = Column(Text, nullable=True)
    doc_pct_classification = Column(Float, nullable=True)
    doc_pct_dacp = Column(Float, nullable=True)
    doc_pct_glossary = Column(Text, nullable=True)
    doc_pct_output = Column(Text, nullable=True)
    doc_pct_dict_glossary = Column(Text, nullable=True)
    doc_pct_dict_usage = Column(Text, nullable=True)
    doc_pct_usage_glossary = Column(Text, nullable=True)
    doc_pct_storage = Column(Float, nullable=True)
    doc_pct_process_input = Column(Text, nullable=True)
    doc_pct_process_output = Column(Text, nullable=True)
    doc_pct_operational_usage = Column(Float, nullable=True)
    doc_pct_auto_computed = Column(Float, nullable=True)
    doc_pct_target = Column(Float, nullable=False)
    doc_pct_applied_dlk = Column(Float, nullable=True)
    app_code = Column(Text, nullable=True)
    operational_entity_code = Column(Text, nullable=True)
    app_base_code = Column(Text, nullable=True)
    app_base_name = Column(Text, nullable=True)
    app_base_cpc = Column(Text, nullable=True)
    app_base_domain = Column(Text, nullable=True)
    app_criticality = Column(Text, nullable=True)
    app_status = Column(Text, nullable=True)
    app_status_nextgen = Column(Text, nullable=True)
    app_strategic_status = Column(Text, nullable=True)
    hosting_mode = Column(Text, nullable=True)
    production_domain = Column(Text, nullable=True)
    operational_entity = Column(Text, nullable=True)
    update_frequency = Column(Text, nullable=True)
    frequency_comment = Column(Text, nullable=False)
    operational_purge_rule = Column(Text, nullable=True)
    is_gdpr_personal = Column(Boolean, nullable=False)
    is_gdpr_sensitive = Column(Boolean, nullable=False)
    is_localized_data = Column(Boolean, nullable=False)
    is_eligible_dq_dashboard = Column(Boolean, nullable=False)
    quality_requirements = Column(Text, nullable=True)
    quality_criteria = Column(Text, nullable=True)
    documentation_criticality = Column(Text, nullable=False)
    status_comment = Column(Text, nullable=True)
    acceptance_threshold = Column(Float, nullable=False)
    contains_dacp_data = Column(Text, nullable=False)
    data_retention_period = Column(Text, nullable=True)
    purge_rule = Column(Text, nullable=True)
    purge_feature_available = Column(Text, nullable=False)
    purge_activation_mode = Column(Text, nullable=False)
    operational_purge_status = Column(Text, nullable=False)
    purge_frequency = Column(Text, nullable=False)
    purge_arbitration = Column(Text, nullable=False)
    purge_method_validated = Column(Text, nullable=False)
    classification_propagation = Column(Text, nullable=False)
    dacp_propagation = Column(Text, nullable=False)
    dependency_other_db = Column(Text, nullable=False)
    underlying_data = Column(Text, nullable=True)
    dataset_ref = Column(Text, nullable=True)
    dataset_filiere = Column(Text, nullable=True)
    it_contact = Column(Text, nullable=True)
    bpi_process_owner = Column(Text, nullable=False)
    justification = Column(Text, nullable=True)
    english_label = Column(Text, nullable=True)
    perimeter = Column(Text, nullable=True)
    functional_grouping = Column(Text, nullable=True)
    usage_link_id = Column(Text, nullable=True)
    programming_language = Column(Text, nullable=True)
    is_optional_control = Column(Boolean, nullable=False)
    created_at = Column(Text, nullable=False)
    updated_at = Column(Text, nullable=False)
    validated_at = Column(Text, nullable=True)
    dacp_review_date = Column(Text, nullable=True)
    classification_review_date = Column(Text, nullable=True)
    doc_pct_last_updated_at = Column(Text, nullable=True)
    release_date = Column(Text, nullable=True)
    summary = Column(Text, nullable=True)
    description = Column(Text, nullable=True)
    parent_uuid = Column(Text, nullable=True)
    parent_type = Column(Text, nullable=True)
    parent_data_type = Column(Text, nullable=True)
    doc_pct_global = Column(Float, nullable=False)
    status_score = Column(Float, nullable=False)
    usage_quality_score = Column(Float, nullable=False)
    usage_quality_status = Column(Text, nullable=False)
    hierarchy_level = Column(BigInteger, nullable=False)
    hierarchy_name = Column(Text, nullable=False)
    source_file = Column(Text, nullable=False)
