export const mockLineageGraph = {
  root: "field_customer_name_src",
  activePath: [
    "field_customer_name_src",
    "edge_input_normalize",
    "dpi_normalize_customer_name",
    "edge_output_payload",
    "payload_customer_name",
    "edge_input_enrich",
    "dpi_enrich_customer_name",
    "edge_output_target",
    "field_customer_name_target",
  ],
  nodes: [
    {
      id: "table_customer_source",
      node_id: "table_customer_source",
      type: "Source",
      name: "customer_source",
      path: "CRM\\raw",
    },
    {
      id: "field_customer_id_src",
      node_id: "field_customer_id_src",
      type: "Field",
      name: "customer_id",
      parent_node_id: "table_customer_source",
      path: "CRM\\raw\\customer_source\\customer_id",
    },
    {
      id: "field_customer_name_src",
      node_id: "field_customer_name_src",
      type: "Field",
      name: "customer_name",
      parent_node_id: "table_customer_source",
      path: "CRM\\raw\\customer_source\\customer_name",
    },
    {
      id: "field_country_src",
      node_id: "field_country_src",
      type: "Field",
      name: "country_code",
      parent_node_id: "table_customer_source",
      path: "CRM\\raw\\customer_source\\country_code",
    },
    {
      id: "dp_normalize_customer",
      node_id: "dp_normalize_customer",
      type: "DataProcessing",
      name: "Normalize customer payload",
      path: "Pipelines\\customer\\normalize",
    },
    {
      id: "dpi_normalize_customer_name",
      node_id: "dpi_normalize_customer_name",
      type: "DataProcessingItem",
      name: "Normalize customer name",
      parent_node_id: "dp_normalize_customer",
      path: "Pipelines\\customer\\normalize\\Normalize customer name",
    },
    {
      id: "dpi_normalize_country",
      node_id: "dpi_normalize_country",
      type: "DataProcessingItem",
      name: "Normalize country",
      parent_node_id: "dp_normalize_customer",
      path: "Pipelines\\customer\\normalize\\Normalize country",
    },
    {
      id: "payload_customer",
      node_id: "payload_customer",
      type: "Structure",
      name: "customer_payload",
      path: "Kafka\\customer\\payload",
    },
    ...[
      "customer_id",
      "customer_name",
      "country_code",
      "email",
      "phone",
      "birth_date",
      "status",
      "segment",
      "last_update",
      "source_system",
      "ingestion_time",
      "record_hash",
    ].map((name) => ({
      id: `payload_${name}`,
      node_id: `payload_${name}`,
      type: "Field",
      name,
      parent_node_id: "payload_customer",
      path: `Kafka\\customer\\payload\\${name}`,
    })),
    {
      id: "dp_enrich_customer",
      node_id: "dp_enrich_customer",
      type: "DataProcessing",
      name: "Enrich customer mart",
      path: "Pipelines\\customer\\enrich",
    },
    ...[
      "Map customer name",
      "Resolve segment",
      "Format status",
      "Apply privacy flag",
      "Build reporting key",
      "Audit timestamps",
      "Validate identifiers",
      "Join reference country",
      "Project final schema",
      "Compute row hash",
      "Prepare target load",
      "Archive payload",
    ].map((name, index) => ({
      id: index === 0 ? "dpi_enrich_customer_name" : `dpi_enrich_${index}`,
      node_id: index === 0 ? "dpi_enrich_customer_name" : `dpi_enrich_${index}`,
      type: "DataProcessingItem",
      name,
      parent_node_id: "dp_enrich_customer",
      path: `Pipelines\\customer\\enrich\\${name}`,
    })),
    {
      id: "table_customer_target",
      node_id: "table_customer_target",
      type: "Structure",
      name: "dim_customer",
      path: "Warehouse\\gold",
    },
    {
      id: "field_customer_key_target",
      node_id: "field_customer_key_target",
      type: "Column",
      name: "customer_key",
      parent_node_id: "table_customer_target",
      path: "Warehouse\\gold\\dim_customer\\customer_key",
    },
    {
      id: "field_customer_name_target",
      node_id: "field_customer_name_target",
      type: "Column",
      name: "customerName",
      parent_node_id: "table_customer_target",
      path: "Warehouse\\gold\\dim_customer\\customerName",
    },
    {
      id: "field_country_target",
      node_id: "field_country_target",
      type: "Column",
      name: "countryCode",
      parent_node_id: "table_customer_target",
      path: "Warehouse\\gold\\dim_customer\\countryCode",
    },
  ],
  edges: [
    { id: "edge_part_normalize_name", source: "dpi_normalize_customer_name", target: "dp_normalize_customer", type: "PART_OF" },
    { id: "edge_part_normalize_country", source: "dpi_normalize_country", target: "dp_normalize_customer", type: "PART_OF" },
    { id: "edge_part_enrich_name", source: "dpi_enrich_customer_name", target: "dp_enrich_customer", type: "PART_OF" },
    {
      id: "edge_input_normalize",
      source: "field_customer_name_src",
      target: "dpi_normalize_customer_name",
      type: "IS_INPUT_OF",
    },
    {
      id: "edge_output_payload",
      source: "payload_customer_name",
      target: "dpi_normalize_customer_name",
      type: "IS_OUTPUT_OF",
    },
    {
      id: "edge_input_enrich",
      source: "payload_customer_name",
      target: "dpi_enrich_customer_name",
      type: "IS_INPUT_OF",
    },
    {
      id: "edge_output_target",
      source: "field_customer_name_target",
      target: "dpi_enrich_customer_name",
      type: "IS_OUTPUT_OF",
    },
    {
      id: "edge_country_flow",
      source: "field_country_src",
      target: "field_country_target",
      type: "FLOWS_TO",
      properties: { via_dpi: "dpi_normalize_country" },
    },
  ],
};
